// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpaceLaunchTracker.Data;

namespace SpaceLaunchTracker.Migrations
{
    [DbContext(typeof(SpaceLaunchTrackerDbContext))]
    partial class SpaceLaunchTrackerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SpaceLaunchTracker.Data.DataModels.AgencyDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AgencyName");

                    b.Property<int?>("CountryId");

                    b.Property<string>("InfoUrl");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Agencies");
                });

            modelBuilder.Entity("SpaceLaunchTracker.Data.DataModels.CountryDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CountryCode");

                    b.HasKey("Id");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("SpaceLaunchTracker.Data.DataModels.LaunchDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AgencyId");

                    b.Property<DateTime>("ChangedTime");

                    b.Property<int?>("CountryId");

                    b.Property<string>("InfoUrl");

                    b.Property<DateTime>("LaunchDate");

                    b.Property<int>("LaunchNumber");

                    b.Property<string>("LaunchSite");

                    b.Property<string>("MissionDetails");

                    b.Property<string>("MissionName");

                    b.Property<string>("RocketName");

                    b.Property<DateTime>("UpdatedTime");

                    b.HasKey("Id");

                    b.HasIndex("AgencyId");

                    b.HasIndex("CountryId");

                    b.ToTable("Launches");
                });

            modelBuilder.Entity("SpaceLaunchTracker.Data.DataModels.AgencyDto", b =>
                {
                    b.HasOne("SpaceLaunchTracker.Data.DataModels.CountryDto", "Country")
                        .WithMany("Agencies")
                        .HasForeignKey("CountryId");
                });

            modelBuilder.Entity("SpaceLaunchTracker.Data.DataModels.LaunchDto", b =>
                {
                    b.HasOne("SpaceLaunchTracker.Data.DataModels.AgencyDto", "Agency")
                        .WithMany("Launches")
                        .HasForeignKey("AgencyId");

                    b.HasOne("SpaceLaunchTracker.Data.DataModels.CountryDto", "Country")
                        .WithMany("Launches")
                        .HasForeignKey("CountryId");
                });
#pragma warning restore 612, 618
        }
    }
}
